### ISSUE TITLE
Allow cave selection from the command line.

### ISSUE THREAD

**Issue by Burglory** [secretsquirrel/the-backdoor-factory#36]
Currently, when patching large exes, use interaction is required everytime to select the proper caves. I think the cave 'table' only needs to be printed once per file. So why not have the caves selected in the command? Because currently, most AV's pick this up and so waiting for the table to show up becomes a pain.

**Comment by secretsquirrel** [comment]
It's printed to show the user what caves are for each section of shellcode.

I'm working on automating the process.  There are reasons for not
automatically doing it right now.

Until then this is how it will be done.


On Jan 25, 2015, at 3:55 PM, Burglory <notifications@github.com> wrote:

Currently, when patching large exes, use interaction is required everytime
to select the proper caves. I think the cave 'table' only needs to be
printed once per file. So why not have the caves selected in the command?
Because currently, most AV's pick this up and so waiting for the table to
show up becomes a pain.

—
Reply to this email directly or view it on GitHub
<https://github.com/secretsquirrel/the-backdoor-factory/issues/36>.
