### ISSUE TITLE
.Apk files support

### ISSUE THREAD

**Issue by ortholinux** [secretsquirrel/the-backdoor-factory#59]
Cant backdoor-factory support apk files somehow, as this feature will be awsome with "bdfproxy" and maybe if don't support the use of payload injection(automatic) or binding(onionduke) like with windows binaries and other OS then perhaps the "replace" method can be used, i.e just replace the legitimate .apk with malicious .apk, the method might not be handy with backdoor-factory itself but would be an awsome feature in bdfproxy.
and if this can be, then please consider this an enhancement request.

**Comment by secretsquirrel** [comment]
Already an issue: https://github.com/secretsquirrel/the-backdoor-factory/issues/26

I accept pull requests!

**Comment by Manouchehri** [comment]
@secretsquirrel I don't think this is quite a duplicate of #26, since there's two ways to backdoor an APK:

1. Backdooring with smali (see https://github.com/dana-at-cp/backdoor-apk), which is basically #26 is asking for
2. Backdooring native (ELF) binaries inside the APK

I think doing option 2 would be easier since the only part missing right now is unpacking and repacking/signing the APK.

Thoughts?

cc @infodox

**Comment by secretsquirrel** [comment]
Good point.  Yeah I've looked at some elf binaries within certain APKs from the play store that would load after manual modification.  Feel free to open an issue to specifically support backdooring native ELF binaries inside the APK. Though to be really useful for APKs, BDF will need a new patching method to support shared object patching as I've seen a lot of those in APKs specifically.
